version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./gym-rest-api/src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./gym-rest-api/src/main/resources/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./gym-rest-api/src/main/resources/grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


  activemq:
    image: apache/activemq-classic
    container_name: activemq
    environment:
      ACTIVEMQ_NAME: 'localhost'
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'true'
      ACTIVEMQ_ADMIN_LOGIN: 'admin'
      ACTIVEMQ_ADMIN_PASSWORD: 'admin'
    ports:
      - "61616:61616" # broker
      - "8161:8161"   # web
    volumes:
      - ./activemq/data:/opt/apache-activemq/data
      - ./activemq/conf/activemq.xml:/opt/apache-activemq/conf/activemq.xml


  mongodb:
    image: mongo:7.0.12
    container_name: ${MONGODB_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: trainer-workload
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  trainer-workload-service:
    build: ./trainer-work-service
    environment:
      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: 8081
      JMS_DESTINATION_MAIN: ${JMS_DESTINATION_MAIN}
    depends_on:
      - activemq
      - mongodb
    ports:
      - "8081:8081"

  gym-rest-api:
    build: ./gym-rest-api
    environment:
      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: 8080
      JMS_DESTINATION_MAIN: ${JMS_DESTINATION_MAIN}
      SPRING_ACTIVE_PROFILE: dev
    depends_on:
      - activemq
    ports:
      - "8080:8080"

volumes:
  grafana-data:
  mongodb-data:
