spring:
  activemq:
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:trainerdb;DB_CLOSE_DELAY=-1
    username: sa
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
    open-in-view: true
  sql:
    init:
      mode: always
  application:
    name: trainer-work-service

messaging:
  jms:
    destination: "workload-queue"

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

security:
  jwt:
    secret: '92898efcc0d1de074c41bec111add6ae654e20c5cb53f0418d68c0ba055fdd17'