spring:
  activemq:
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
    packages:
      trust-all: true
  application:
    name: trainer-work-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainer-workload
      authentication-database: admin
      auto-index-creation: true
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
    open-in-view: true
  sql:
    init:
      mode: always

security:
  jwt:
    secret: '92898efcc0d1de074c41bec111add6ae654e20c5cb53f0418d68c0ba055fdd17'

server:
  port: 8081

messaging:
  jms:
    destinations:
      main: "workload-queue"